apiVersion: v1
data:
  mapRoles: |
   - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::739109788295 :role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::739109788295 :role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-12T08:26:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-02-12T08:26:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1700"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6dddc20e-9c5a-4fe7-9648-7fee03aacf54
